### ISSUE TITLE
ShutdownMonitor.py using gpio16 not working

### ISSUE THREAD

**Issue by BDBAfH** [kwindrem/ShutdownMonitor#1]
Hi,

many thanks for your repos.
I have installed the ShutdownMonitor V2.0 and it works fine from Console.
My goal is to use a litte USV solution which will shutdown the Venus device in case of power loss by setting gpio16 to low.

Unfortunately the device files for gpio16 are not created during setup of ShutdownMonitor.
The console switch "Enable shutdown pin" is set to on.

After manually editing /etc/venus/gpio_list the device files are created and the system goes down in case of power loss.

Because /etc/venus/gpio_list is a system file which can modified by updates from Victron please can you create the nessecary device files during setup?

Many thanks
Michael

**Comment by kwindrem** [comment]
For the GPIO to work, you must also install RpiGpioSetup.

I though I'd included that in the ReadMe but it is not there so I'll add it as part of the next release.

**Comment by BDBAfH** [comment]
Thanks.
After installing RpiGpioSetup Gpio16 is available.
