### ISSUE TITLE
"gzip: invalid magic" error following installation instructions

### ISSUE THREAD

**Issue by OutsourcedGuru** [kwindrem/ShutdownMonitor#4]
Attempting to follow [these](https://off-grid-garage.com/victron-venus-os-shutdown-feature/) installation instructions, the first command works and the second results in the following:

```
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Attempting to do the following then...

```
mkdir /data/tmp && cd /data/tmp
wget https://github.com/kwindrem/ShutdownMonitor/archive/current.tar.gz

--2023-07-27 01:42:09--  https://github.com/kwindrem/ShutdownMonitor/archive/current.tar.gz
Resolving github.com... 140.82.113.4
Connecting to github.com|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/kwindrem/ShutdownMonitor/tar.gz/current [following]
--2023-07-27 01:42:10--  https://codeload.github.com/kwindrem/ShutdownMonitor/tar.gz/current
Resolving codeload.github.com... 140.82.114.9
Connecting to codeload.github.com|140.82.114.9|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-07-27 01:42:11 ERROR 404: Not Found.
```

In theory, this should be a work-around for the moment...

```
mkdir /data/tmp && cd /data/tmp
wget https://github.com/kwindrem/ShutdownMonitor/archive/refs/heads/main.zip
unzip main.zip
rm /data/tmp/main.zip
mv /data/tmp/ShutdownMonitor-main /data/ShutdownMonitor
cd /data
rmdir /data/tmp
```

Using this method, I was able to install the ShutdownMonitor, see it in the Settings -> General screen and exercise it to shutdown the Pi.

**Comment by kwindrem** [comment]
There is no "current" branch or tag. You need to use "latest"

main typically has the same revisions as latest but it's not a good reference for download.

The instructions in the ReadMe are incorrect and I'll fix that.

**Comment by kwindrem** [comment]
Just checked and you referenced instructions from someone else and it is their documentation that is not correct.
